import fs from 'fs';
import path from 'path';
import { findYamlFiles, parseYamlFile } from './utils/yaml_utils.js';
import { parseCsv } from './utils/csv_utils.js';
import { buildReproducedStates, extractLastRunDate } from './utils/regression_utils.js';

const EXPECTED_HEADER = ['example_id', 'type', 'is_reproduced'];

function generateTypeScriptContent(errorStates, exampleStates, lastRunDate) {
	return `// This file is auto-generated by scripts/gen_regression_data.js
// Do not edit manually

export type ReproducedState = 'reproduced' | 'not_reproduced' | 'untested';

export const lastRunDate: string | null = ${JSON.stringify(lastRunDate)};

export const errorReproducedStates: Record<string, ReproducedState> = ${JSON.stringify(errorStates, null, 2)};

export const exampleReproducedStates: Record<string, { full: ReproducedState; minified: ReproducedState }> = ${JSON.stringify(exampleStates, null, 2)};
`;
}

function main() {
	const foundIssuesArg = process.argv[2];
	const csvPathArg = process.argv[3];
	const outputPathArg = process.argv[4];
	if (!foundIssuesArg || !csvPathArg || !outputPathArg) {
		console.error('Usage: node scripts/gen_regression_data.js <found_issues_dir> <regression_csv> <output_ts_path> [run_metadata_json]');
		process.exit(1);
	}
	const metadataPathArg = process.argv[5];

	const foundIssuesDir = path.resolve(process.cwd(), foundIssuesArg);
	const csvPath = path.resolve(process.cwd(), csvPathArg);
	const outputFile = path.resolve(process.cwd(), outputPathArg);

	let lastRunDate = null;
	if (metadataPathArg) {
		const metadataPath = path.resolve(process.cwd(), metadataPathArg);
		const raw = fs.existsSync(metadataPath) ? fs.readFileSync(metadataPath, 'utf8') : null;
		if (raw === null) {
			console.warn(`! Run metadata not found at ${metadataPath} — lastRunDate will be null.`);
		}
		lastRunDate = extractLastRunDate(raw);
	}

	const foundErrors = findYamlFiles(foundIssuesDir)
		.map(parseYamlFile)
		.filter((e) => e !== null);

	let rows = [];
	if (fs.existsSync(csvPath)) {
		const { header, rows: csvRows } = parseCsv(fs.readFileSync(csvPath, 'utf8'));
		const headerOk = header.length === EXPECTED_HEADER.length && header.every((col, i) => col.trim() === EXPECTED_HEADER[i]);
		if (!headerOk) {
			console.error('Regression CSV header mismatch.');
			console.error('Expected:', EXPECTED_HEADER.join(','));
			console.error('Got:     ', header.join(','));
			process.exit(1);
		}
		rows = csvRows;
	} else {
		console.warn(`! Regression CSV not found at ${csvPath} — emitting all-untested states.`);
	}

	const { errorReproducedStates, exampleReproducedStates } = buildReproducedStates(foundErrors, rows);

	const outputDir = path.dirname(outputFile);
	if (!fs.existsSync(outputDir)) {
		fs.mkdirSync(outputDir, { recursive: true });
	}
	fs.writeFileSync(outputFile, generateTypeScriptContent(errorReproducedStates, exampleReproducedStates, lastRunDate));
	console.log(
		`Generated regression TS file: ${outputFile} ` +
			`(${Object.keys(errorReproducedStates).length} errors, ${Object.keys(exampleReproducedStates).length} examples)`
	);
}

main();
