import fs from 'fs';
import path from 'path';
import { readCsvFile } from './utils/csv_utils.js';

const EXPECTED_HEADER = [
  'error_id',
  'runs_for_that_issue',
  'overall_found_count',
  'test_files_count',
  'last_occurrence_tool_commit',
  'last_occurrence_date',
  'last_model_commit'
];

function generateTypeScriptContent(stats) {
  return `// This file is auto-generated by scripts/gen_stats_data.js
// Do not edit manually

export type ErrorStat = {
\terror_id: string;
\toverall: number;
\ttest_files_count: number;
\truns: number;
\tlast_commit: string;
\tlast_date: string;
};

export const errorsStats: Record<string, ErrorStat> = ${JSON.stringify(stats, null, 2)};
`;
}

function main() {
  const csvPathArg = process.argv[2];
  const outputPathArg = process.argv[3];
  if (!csvPathArg || !outputPathArg) {
    console.error('Usage: node scripts/gen_stats_data.js <path_to_combined_stats.csv> <output_ts_path>');
    process.exit(1);
  }

  const csvPath = path.resolve(process.cwd(), csvPathArg);
  if (!fs.existsSync(csvPath)) {
    console.error(`combined_stats.csv not found at ${csvPath}`);
    process.exit(1);
  }

  const { header, rows } = readCsvFile(csvPath);
  if (header.length !== EXPECTED_HEADER.length || !header.every((col, i) => col === EXPECTED_HEADER[i])) {
    console.error('CSV header mismatch.');
    console.error('Expected:', EXPECTED_HEADER.join(','));
    console.error('Got:     ', header.join(','));
    process.exit(1);
  }

  const stats = {};
  for (const row of rows) {
    const [error_id, runs, overall, test_files_count, last_commit, last_date /* , last_model_commit (ignored) */] = row;
    stats[error_id] = {
      error_id,
      overall: Number(overall),
      test_files_count: Number(test_files_count),
      runs: Number(runs),
      last_commit,
      last_date
    };
  }

  const outputFile = path.resolve(process.cwd(), outputPathArg);
  const outputDir = path.dirname(outputFile);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  fs.writeFileSync(outputFile, generateTypeScriptContent(stats));
  console.log(`Generated stats TS file: ${outputFile} (${Object.keys(stats).length} entries)`);
}

main();
