---
name: Build and test

on:
  push:
    branches:
      - main
      - master
    tags:
      - "**"
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: "0 1 * * *"

permissions: read-all

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  PACK_DIR: /root/.pack
  GENERATION_DIR_PATTERN: "generated-"
  GEN_TESTS_COUNT: 256
  BUILD_DIR: ".build"
  PACKAGE_NAME: verilog-model
  ERROR_DISTANCES_OUT: error_distances.html
  GH_PAGES_PATH: verilog-gh-pages
  RUN_STATS_PATTERN: "run-stats.json"
  COMBINED_RUN_STATS_FILE: "combined-run-stats.json"
  UNKNOWN_ERRORS_OUT: "unknown_errors.json"
  REGRESSION_UNKNOWN_ERRORS_PATTERN: "regression-unknown-errors"

jobs:
  get-upstream-matrix:
    name: Acquire matrix of upstream modes
    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    outputs:
      upstream-matrix: "${{ steps.get-upstream-matrix.outputs.upstream-matrix }}"
    steps:
      - name: Install Git
        run: apt-get update && apt-get install git
      - name: Get upstream matrix
        id: get-upstream-matrix
        run: |
          CURR="$(idris2 --version | sed 's/.*-//')"
          MAIN="$(git ls-remote https://github.com/idris-lang/Idris2 main | head -c 9)"
          echo "Current: $CURR, bleeding edge: $MAIN"
          if [ "$CURR" == "$MAIN" ]; then
            echo 'upstream-matrix=["latest-pack-collection"]'
          else
            echo 'upstream-matrix=["latest-pack-collection", "bleeding-edge-compiler"]'
          fi >> "$GITHUB_OUTPUT"

  build-and-test:
    name: Build and test `${{ github.repository }}`
    needs: get-upstream-matrix
    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    outputs:
      latest-cache-key: ${{ steps.export-key.outputs.latest_key }}
      build-path: ${{ steps.export-key.outputs.build_path }}
    strategy:
      fail-fast: false
      matrix:
        upstream-mode: ${{ fromJSON(needs.get-upstream-matrix.outputs.upstream-matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Update `pack-db`
        run: pack update-db
      - name: Switch to the latest compiler, if needed
        if: matrix.upstream-mode == 'bleeding-edge-compiler'
        run: |
          { echo; echo "[idris2]"; echo 'commit = "latest:main"'; } >> pack.toml
          pack fetch
      - name: Switch to the latest collection
        run: pack switch latest
      - name: Calculate cache key
        id: cache-key
        run: |
          idris2_commit=$(idris2 -v | sed -nE 's/.*Idris 2, version [0-9.]+-([A-Za-z0-9]+).*/\1/p')
          echo "key=build-${{ hashFiles('src/**', 'verilog-model.ipkg', 'pack.toml') }}-${{ matrix.upstream-mode }}-$idris2_commit" >> "$GITHUB_OUTPUT"
      - name: Export key
        id: export-key
        if: matrix.upstream-mode == 'latest-pack-collection'
        run: |
          echo "latest_key=${{ steps.cache-key.outputs.key }}" >> "$GITHUB_OUTPUT"
          echo "build_path=$PWD" >> "$GITHUB_OUTPUT"
      - name: Restore from cache
        id: cache-build
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.BUILD_DIR }}
          key: ${{ steps.cache-key.outputs.key }}
      - name: Touch files
        if: steps.cache-build.outputs.cache-hit == 'true'
        run: |
          find "${{ env.BUILD_DIR }}" -type f -exec touch {} +
          sync
      - name: Build `${{ env.PACKAGE_NAME }}`
        run: pack build ${{ env.PACKAGE_NAME }}
      - name: Save build
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: ${{ env.BUILD_DIR }}
          key: ${{ steps.cache-key.outputs.key }}
      # - name: Fix file system  ¯\_(ツ)_/¯
      #   run: |
      #     set -x +e
      #     pack run ${{ env.PACKAGE_NAME }} --coverage mcov -n 1 --seed 0,1
      #     touch tests/printer/model-coverage/dummy
      #     touch tests/printer/create-dir/dummy
      # - name: Test ${{ env.PACKAGE_NAME }}
      #   run: pack test ${{ env.PACKAGE_NAME }}

  generate-modules:
    name: Generate ${{ matrix.language }} files
    needs: build-and-test
    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    strategy:
      fail-fast: false
      matrix:
        language: [sv, vhdl]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Update `pack-db`
        run: pack update-db
      - name: Switch to the latest collection
        run: pack switch latest
      - name: Restore from cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.BUILD_DIR }}
          key: ${{ needs.build-and-test.outputs.latest-cache-key }}
          fail-on-cache-miss: true
      - name: Touch files
        run: |
          find "${{ env.BUILD_DIR }}" -type f -exec touch {} +
          sync
      - name: Set env vars
        run: |
          echo "OUT_DIR=${{ env.GENERATION_DIR_PATTERN }}${{ matrix.language }}" >> "$GITHUB_ENV"
          echo "COV_DIR=mcov_${{ matrix.language }}" >> "$GITHUB_ENV"
      - name: Generate modules
        run: |
          pack run ${{ env.PACKAGE_NAME }} \
            --to "${{ env.OUT_DIR }}" \
            -n ${{ env.GEN_TESTS_COUNT }} \
            --lang ${{ matrix.language }} \
            --seed-name \
            --seed-content \
            --coverage "${{ env.COV_DIR }}"
      - name: Show coverage
        run: cat ${{ env.COV_DIR }}
      - uses: actions/upload-artifact@v6
        with:
          name: "${{ env.GENERATION_DIR_PATTERN }}${{ matrix.language }}"
          path: "${{ env.OUT_DIR }}"

  get-tool-matrix:
    name: Build tool matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: "${{ steps.gen.outputs.matrix }}"
      check-matrix: "${{ steps.gen.outputs.check-matrix }}"
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install requirements
        run: pip install -r ci/runner/gen_matrix/requirements.txt
      - name: Generate matrix
        id: gen
        run: cd ci/runner && python -m gen_matrix.main

  get-test-matrix:
    name: Discover test suites
    runs-on: ubuntu-latest
    outputs:
      matrix: "${{ steps.discover.outputs.matrix }}"
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Discover suites
        id: discover
        run: cd ci/runner && python gen_test_matrix.py

  test-python-units:
    name: Test ${{ matrix.suite.name }}
    runs-on: ubuntu-latest
    needs: get-test-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.get-test-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install requirements
        if: ${{ matrix.suite.requirements }}
        run: |
          cd ci/runner
          pip install -r ${{ matrix.suite.requirements }}
      - name: Run tests
        working-directory: ci/runner
        run: python -m ${{ matrix.suite.name }}.tests.test

  run-tools:
    name: ${{ matrix.tool.name }}
    needs: [test-python-units, generate-modules, get-tool-matrix]
    timeout-minutes: 90
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.get-tool-matrix.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Determine Gen Path
        run: |
          echo "GEN_PATH=${{ env.GENERATION_DIR_PATTERN }}${{ matrix.tool.language }}" >> "$GITHUB_ENV"
      - name: Download Generated Files
        uses: actions/download-artifact@v8
        with:
          name: "${{ env.GEN_PATH }}"
          path: "${{ env.GEN_PATH }}"
      - name: Setup tool
        uses: ./.github/actions/setup-tool
        with:
          tool-name: ${{ matrix.tool.name }}
          tool-repo: ${{ matrix.tool.repo }}
          tool-path: ${{ matrix.tool.path }}
          tool-build: ${{ matrix.tool.build }}
          tool-install: ${{ matrix.tool.install }}
          tool-deps: ${{ matrix.tool.deps }}
          tool-version: ${{ matrix.tool.version }}
          tool-rust-ver: ${{ matrix.tool.rust_ver }}
          tool-pre-build: ${{ matrix.tool.pre_build }}
          tool-third-party-release-repo: ${{ matrix.tool.third_party_release_repo }}
          tool-third-party-release-name-wildcard: ${{ matrix.tool.third_party_release_name_wildcard }}
      - name: Install runner deps
        run: sudo apt install -y bc python3 python3-pip python3-venv
      - name: Setup python venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install -r ci/runner/tools_run/requirements.txt
          if [ -n "${{ matrix.tool.python_runner_deps }}" ]; then
            pip install ${{ matrix.tool.python_runner_deps }}
          fi
      - name: Clone gh-pages
        run: git clone https://github.com/DepTyCheck/verilog-model.git --branch gh-pages --single-branch ${{ env.GH_PAGES_PATH }}
      - name: Run
        run: |
          set +e
          source .venv/bin/activate

          cd "${{ env.GH_PAGES_PATH }}"
          echo "Latest commit hash of ${{ env.GH_PAGES_PATH }}:"
          git rev-parse HEAD
          cd -

          cd ci/runner && python3 -m tools_run.main \
            --gen-path "${{ env.GEN_PATH }}" \
            --file-pattern "${{ matrix.tool.file_pattern }}" \
            --job-link "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ github.job }}" \
            --tool-name "${{ matrix.tool.name }}" \
            --commands-json '${{ toJSON(matrix.tool.commands) }}' \
            --ignored-errors-dir "${{ env.GH_PAGES_PATH }}/found_errors/${{ matrix.tool.path }}" \
            --unknown-errors-output "${{ env.UNKNOWN_ERRORS_OUT }}" \
            --run-statistics-output "${{ matrix.tool.name }}-${{ env.RUN_STATS_PATTERN }}" \
            --commit "${{ env.COMMIT_HASH }}" \
            --assets ${{ matrix.tool.assets }} \
            --extra-ignored-regexes ${{ matrix.tool.extra_ignored_regexes }}

          EXIT_CODE=$?
          if [ $EXIT_CODE -ne 0 ]; then
                exit 1
          fi
      - name: Upload run statistics
        uses: actions/upload-artifact@v6
        with:
          name: "${{ matrix.tool.name }}-${{ env.RUN_STATS_PATTERN }}"
          path: "${{ matrix.tool.name }}-${{ env.RUN_STATS_PATTERN }}"
      - name: Install mds_report dependencies
        if: failure()
        run: |
          source .venv/bin/activate
          pip install -r ci/runner/mds_report/requirements.txt
      - name: Generate MDS diagram
        if: failure() && hashFiles(env.UNKNOWN_ERRORS_OUT) != ''
        run: |
          source .venv/bin/activate
          cd ci/runner && python3 -m mds_report.main \
            --unknown-errors-input "$GITHUB_WORKSPACE/${{ env.UNKNOWN_ERRORS_OUT }}" \
            --ignored-errors-dir "${{ env.GH_PAGES_PATH }}/found_errors/${{ matrix.tool.path }}" \
            --tool-name "${{ matrix.tool.name }}" \
            --job-link "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ github.job }}" \
            --output "${{ env.ERROR_DISTANCES_OUT }}"
      - name: Upload error distances artifact
        if: failure() && hashFiles(env.ERROR_DISTANCES_OUT) != ''
        uses: actions/upload-artifact@v6
        with:
          name: error-distances-${{ matrix.tool.name }}
          path: ${{ env.ERROR_DISTANCES_OUT }}

  regression-test:
    name: Regression test ${{ matrix.tool.name }}
    runs-on: ubuntu-latest
    needs: [test-python-units, get-tool-matrix, run-tools]
    if: always()
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.get-tool-matrix.outputs.check-matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup tool
        uses: ./.github/actions/setup-tool
        with:
          tool-name: ${{ matrix.tool.name }}
          tool-repo: ${{ matrix.tool.repo }}
          tool-path: ${{ matrix.tool.path }}
          tool-build: ${{ matrix.tool.build }}
          tool-install: ${{ matrix.tool.install }}
          tool-deps: ${{ matrix.tool.deps }}
          tool-version: ${{ matrix.tool.version }}
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install Python dependencies
        run: pip install -r ci/runner/regression_test/requirements.txt
      - name: Clone gh-pages
        run: git clone https://github.com/DepTyCheck/verilog-model.git --branch gh-pages --single-branch ${{ env.GH_PAGES_PATH }}
      - name: Run regression test
        run: |
          cd ci/runner && python -m regression_test.main \
            --known-errors-dir "$GITHUB_WORKSPACE/${{ env.GH_PAGES_PATH }}/found_errors" \
            --output "$GITHUB_WORKSPACE/regression-test-report-${{ matrix.tool.name }}.json" \
            --tool-name "${{ matrix.tool.name }}" \
            --commands-json '${{ toJSON(matrix.tool.commands) }}' \
            --language "${{ matrix.tool.language }}" \
            --language-config "$GITHUB_WORKSPACE/ci/conf/languages.yaml" \
            --error-url-prefix "https://${{ github.repository_owner }}.github.io/${{ env.PACKAGE_NAME }}/error" \
            --unknown-errors-output "$GITHUB_WORKSPACE/${{ env.REGRESSION_UNKNOWN_ERRORS_PATTERN }}-${{ matrix.tool.name }}.json" \
            --assets ${{ matrix.tool.assets }} \
            --extra-ignored-regexes ${{ matrix.tool.extra_ignored_regexes }} \
            >> "$GITHUB_STEP_SUMMARY"
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: regression-test-report-${{ matrix.tool.name }}
          path: regression-test-report-${{ matrix.tool.name }}.json
      - name: Install mds_report dependencies
        if: failure()
        run: pip install -r ci/runner/mds_report/requirements.txt
      - name: Generate MDS diagram
        if: failure() && hashFiles(format('{0}-{1}.json', env.REGRESSION_UNKNOWN_ERRORS_PATTERN, matrix.tool.name)) != ''
        run: |
          cd ci/runner && python -m mds_report.main \
            --unknown-errors-input "$GITHUB_WORKSPACE/${{ env.REGRESSION_UNKNOWN_ERRORS_PATTERN }}-${{ matrix.tool.name }}.json" \
            --ignored-errors-dir "$GITHUB_WORKSPACE/${{ env.GH_PAGES_PATH }}/found_errors/${{ matrix.tool.path }}" \
            --tool-name "${{ matrix.tool.name }}" \
            --job-link "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ github.job }}" \
            --output "regression-error-distances-${{ matrix.tool.name }}.html"
      - name: Upload regression MDS artifact
        if: failure() && hashFiles(format('regression-error-distances-{0}.html', matrix.tool.name)) != ''
        uses: actions/upload-artifact@v6
        with:
          name: regression-error-distances-${{ matrix.tool.name }}
          path: regression-error-distances-${{ matrix.tool.name }}.html

  count-lines:
    name: Count lines of specification
    runs-on: ubuntu-latest
    needs: test-python-units
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Count lines
        run: |
          cd ci/runner && python -m count_lines.main "$GITHUB_WORKSPACE/src" >> "$GITHUB_STEP_SUMMARY"

  compare-errors-stats:
    name: Compare errors stats
    runs-on: ubuntu-latest
    needs: [test-python-units, run-tools, regression-test]
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Download run statistics
        uses: actions/download-artifact@v8
        with:
          path: run-stats
          pattern: "*-${{ env.RUN_STATS_PATTERN }}"
          merge-multiple: true
      - name: Download regression test reports
        uses: actions/download-artifact@v8
        with:
          path: known-errors-reports
          pattern: "regression-test-report-*"
          merge-multiple: true
      - name: Clone gh-pages
        run: git clone https://github.com/DepTyCheck/verilog-model.git --branch gh-pages --single-branch ${{ env.GH_PAGES_PATH }}
      - name: Compare errors
        run: |
          cd ci/runner
          python -m compare_errors.main \
            --previous-report "$GITHUB_WORKSPACE/${{ env.GH_PAGES_PATH }}/src/lib/data/errors-stats.json" \
            --current-tools-reports-dir "$GITHUB_WORKSPACE/run-stats" \
            --tools-reports-pattern "*-${{ env.RUN_STATS_PATTERN }}" \
            --tests-number ${{ env.GEN_TESTS_COUNT }} \
            --error-url-prefix "https://${{ github.repository_owner }}.github.io/${{ env.PACKAGE_NAME }}/error" \
            --known-errors-reports-dir "$GITHUB_WORKSPACE/known-errors-reports" \
            >> "$GITHUB_STEP_SUMMARY"

  push-run-stats:
    name: Push run stats
    runs-on: ubuntu-latest
    needs: [test-python-units, run-tools]
    if: ${{ github.ref == 'refs/heads/master' }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT_PUSH }} # https://stackoverflow.com/a/77447725/15776812
          persist-credentials: false # https://github.com/orgs/community/discussions/25702#discussioncomment-3248819

      - name: Download run statistics
        uses: actions/download-artifact@v8
        with:
          path: run-stats

      - name: Clone gh-pages
        run: git clone https://github.com/DepTyCheck/verilog-model.git --branch gh-pages --single-branch ${{ env.GH_PAGES_PATH }}

      - name: Calc report path
        run: |
          RELATIVE_REPORT_PATH="src/lib/data/errors-stats.json"
          echo "RELATIVE_REPORT_PATH=$RELATIVE_REPORT_PATH" >> "$GITHUB_ENV"
          echo "REPORT_PATH=${{ env.GH_PAGES_PATH }}/$RELATIVE_REPORT_PATH" >> "$GITHUB_ENV"

      - name: Combine statistics
        run: |
          cd ci/runner
          python -m combined_report.main \
            --previous-report "$GITHUB_WORKSPACE/${{ env.REPORT_PATH }}" \
            --current-tools-reports-dir "$GITHUB_WORKSPACE/run-stats" \
            --tools-reports-pattern "*-run-stats.json" \
            --result-report "$GITHUB_WORKSPACE/${{ env.REPORT_PATH }}" \
            --tests-number ${{ env.GEN_TESTS_COUNT }}

      - name: Bot Details
        id: bot-details
        uses: raven-actions/bot-details@v1

      - name: Commit & push
        run: |
          cd ${{ env.GH_PAGES_PATH }}
          git config --global user.name "${{ steps.bot-details.outputs.name }}"
          git config --global user.email "${{ steps.bot-details.outputs.email }}"
          git add ${{ env.RELATIVE_REPORT_PATH }}
          git commit -m "[ bot ] Update runs statistics"
          git remote set-url origin "https://x-access-token:${{ secrets.PAT_PUSH }}@github.com/${{ github.repository }}"
          git push origin gh-pages

  publish-container:
    name: Build and publish Docker image
    needs: [build-and-test, run-tools]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Restore from cache
        id: cache-build
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.BUILD_DIR }}
          key: ${{ needs.build-and-test.outputs.latest-cache-key }}
      - name: Touch ${{ env.BUILD_DIR }} dir (-_-)
        run: |
          set +e
          ls -la
          mkdir ${{ env.BUILD_DIR }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ github.ref }},enable={{is_not_default_branch}}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            WORK_DIR=${{ needs.build-and-test.outputs.build-path }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  create-issue-on-failure:
    name: Create an issue on failure
    if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: [get-upstream-matrix, build-and-test, run-tools, regression-test]
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Read and Format Usernames
        run: |
          TAGGED_USERS=$(awk '{printf "@%s ", $0}' MAINTAINERS)
          echo "TAGGED_USERS=${TAGGED_USERS}" >> "$GITHUB_ENV"
      - name: Create Issue
        uses: actions/github-script@v7
        with:
          script: |
            const issueTitle = `Workflow Failed: ${context.workflow} #${context.runNumber}`;
            const issueBody = `
            Workflow Run: [${context.runNumber}](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})

            Tagging: ${{ env.TAGGED_USERS }}

            Please check the logs for more details
            `;

            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
            });
