name: Build & Deploy website

on:
  pull_request:
    branches:
      - gh-pages
  push:
    branches:
      - gh-pages
  workflow_call:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: gh-pages

      - name: Checkout dataset branch
        uses: actions/checkout@v6
        with:
          ref: dataset
          path: dataset

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Bootstrap & generate
        run: npm run pre

      - name: Run tests
        run: npm run test

  build-site:
    name: Build site
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: gh-pages

      - name: Checkout dataset branch
        uses: actions/checkout@v6
        with:
          ref: dataset
          path: dataset

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: build

  deploy:
    name: Deploy site
    needs: [build-site]
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/gh-pages' || github.ref == 'refs/heads/dataset' }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5
