name: PR Validation

on:
  pull_request:
    branches:
      - gh-pages
  push:
    branches:
      - gh-pages

permissions: read-all

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Checkout dataset branch
        uses: actions/checkout@v6
        with:
          ref: dataset
          path: dataset

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Bootstrap & generate
        run: npm run pre

      - name: Run tests
        run: npm run test

  build-site:
    name: Build site
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout dataset branch
        uses: actions/checkout@v6
        with:
          ref: dataset
          path: dataset

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          npm run build
